# exclude schema file from all cops
AllCops:
  Exclude:
    - db/
# ignore string literals
StringLiterals:
  Enabled: false
# extend line length
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 35
# ignore documentation comments
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false